name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Set your desired Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the Go binary
      - name: Build
        run: go build -o gitsetrun

      # Save the built binary as an artifact
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-binary
          path: gitsetrun
